### ISSUE TITLE
500 Internal error String indices must be integer

### ISSUE THREAD

**Issue by yodatak** [adriaaah/monit-dashboard#6]
With a clean install i got 
```
./bin/monit-dashboard.py
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/web/application.py", line 239, in process
    return self.handle()
  File "/usr/lib/python2.7/site-packages/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/lib/python2.7/site-packages/web/application.py", line 462, in _delegate
    return handle_class(cls)
  File "/usr/lib/python2.7/site-packages/web/application.py", line 438, in handle_class
    return tocall(*args)
  File "./bin/monit-dashboard.py", line 72, in GET
    return render.index(output=getMonit(), now=datetime.datetime.now())
  File "./bin/monit-dashboard.py", line 48, in getMonit
    name = service['name']
TypeError: string indices must be integers

```
Any idea how fix the issue ?

**Comment by yodatak** [comment]
Ok so it's append if there is no process and only system

**Comment by yodatak** [comment]
So i can fix :p
